language: node_js
node_js:
- '4.2'

env:
  global:
  - secure: EwMe+Ws70u10CvK34TnW5Rd3Oau9fUZ0CWqdmtpPLozM6ODWDl5JRl806Kt2PrLiww0eeLdNupF1g5atOKa/vizmD07Z2rpuG7h2U0E2p9cmo/XO4lhVBoGYBbMWNVZofV3lKm5QU7yHqpMH0tzQ5hD53k1cOtsnR7DwV5dhAvP34QqZXjh46/4DKr/XA70sAfN1pz+Y+KxkcrqfgyxCv4ADJqf4m81+jfAghVFx7YiVXT1XLvLbT0EWhOWAdq1werBUJbcdBv67tQxa9jQ4W9IJhNRKV0mfRK7/gnSK5b0flJdeUwT/roX6ZFoZkbuPHT11STXAdOQzvWhF9Or7qKh18oolMwGvhPBvKw4MRc3ueispKe3ZQ9nDzORNAx5RCRW4j9cC99dH4l2WMDg30Lmf4o3/8uBlEklsR/9QxOQtDi65kIx/FEPUwDwtcyaERDZAp5ywgguDVyypd1fOEk0dYi+dYaERT165jaTGY5peUGBcWfEWeCZEWHzrjibQh8RTosCOacoMgr6tLLZZVPEhSAeDSdE5d72775FP666/gzXc2uYjIxsz4zUYTQsQngOO4w+QXbEZmfV0TAm+l+2PWBGraBjFakDA/WyWNMyFiHa7XFzffEUxaNLHwVT8XRIHIszKyiesR+c4T4ROwRdNoZrFHY576rs+i6XChPE=
  - secure: xzGyti59FVfFTPvgPu28DZj0DizujYBdVMciDyGw+DDuvwWedKgjPND4cDzi38WMVLNpWXYfWifpFt431S5LvWRTLMuylL+SOOq/FkzTn8uOLHwHES0E1X4GUbpQA4WMDX8FbfVoiMeCfg9TSzSFPh2RJXZcyNoHtAbNKGrwHk0OnicDew1yTc8k+l6jNhRC3CULCf6MJDSj4b5LsP1CcLBuzXuEdEKD8M24+iYHhfYQ1ObIhqvzaroZIlqzmMcHTNt4mILfAa04DiWMh823rxabyr01Cs5atWyw7wQJVqeKTpYA/zGnP5IYUqMC+zAWuJAiiBEIIzWBV8IwG2sh3vU0vNtTXXGUlv2LMKhsGMxaUZACrpRVyXqIq18ZFanDMMoAapaigswQFT4qLmrsJnrykLrRyz1ueHJfIvJwAhE3Nsj+Rh10Zjn0IfrERnjrMfGcHh62MqP4cIJnrEC4Qb3vItNix8YIVq8T3QYDlYKZdy21JSq5PoHiYjtyrIpuq9UKVZEbgLPmsaO/KZL7ExIvm+SmZYHM1fs8Dli6U+BBT9V6KITrr3VICCcLiY4lzqN7O0AQZfm1CqnmnKZMNo49vnMza/JiEWug31g9B0sOWDsJFh3DNc8UrrjtkM755j3lyCzsSwvQcRBhDrmaoXmeJJ4p4mZbdtJsAIUYUKQ=
  - secure: IohwP8xbWogEZHeGMWu+8wtbLy81zH1Q4rip/D63Tjo+MvEex7YUKtxMp2So24inmndCj8+1fRUlIu1MgEewUXhsME4vvyb7Xw4Td3NjKFwMO2yerwT1cUf/bZxtpU/qkdmBl2Y9LEZrS7if+xl4V/l5294sWhMThVe20acOBOtpf1rdKyU6or8+wBVrfTSsqowbLZAjR40ihdvXCop7nBlxnF8H+FM3H5sdhWf4c8ozK6kx5W1pUZsl27Yn3O4op12aJuOCIYG4obUwn5pz7flH5btJoN59xrS9AfbBWMmdKc2ZHvjXNJD5PzZZ5J2/uFOZUUoV1XXT+FPFONwwE/RcevdoyY1WvoZOwUgk38lCTuPu+gXKOjG9Rk/pVtyX8AETQ2HFxaSKAO6Bas52ppd9z6jWd1nmgH9eBa2kOvsXYZS9SuEGHaxaHggKzgDx39avSsDhOFHUX5ePbDYaTAELYIUZA4ch7KIjxqXcrnUR0tq/06EIypX941mhfuLId3C7y0VCdFRaguD38uX1Qr3DpxWBnpTTjgB1sPDYAp/PC0y+EhfTcmvp0TOTG+0cX1zwqdimbFhRVEjdiWl5H678cDBdknDpXz8nFUYgzl1RZDsU42yV2SYQmE4O8nuOLCGtnFeRK9FE48LqTq7kWXAo4dZJ6BokM60J3CmRiec=

before_deploy:
- sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    tags: true
