language: node_js
node_js:
  - '4.2'

env:
  global:
  - secure: M5ZR4XuTuhXTPNsGY1QlLF+Ri1VSc+5D6bGVRj2hf4CzIZ54oiTEn8FnCpm/BWT0RoG5WNlTSfLGB5Ry47aD6eGBaBc/M0eBEWvGismrS4RAHJVagZtPwMWD5ofXFNi/dDnrJlzv9cOhyNRZ0SbGdRocBXTHm3QoZFqGUHzXcD7fmhZGXAcFxcSJFitc7QJUxWvJ1gTBfcG+qHV7rrO+aaiX74JLs+uY2BKz9Ei/dE8NI+oESdRDb5L4LKIzSG086y9Jwmt3Ul0gJKbr9awBu2tjMwTyp6dpD35zIsfWmXcvqPGU5Wem7HIaN2hqLE7AVlHeDIkCNEjlOQGqLRd1/z0JbHBzu9KMULNUiowZhjd0C4usVHpZwYoxXo3E+zUJRkGQFgzW9p+25sL5+JYyw8f74UyTN9BLpw8+/mlMIbyjj0iFEI/DyXEYb7HCwWOUVWljhN63Ox789+Fj0ImztdW7/7jdP5YTtMCz1oh1tSIRn815SBZT8pKjL7puQf9y3azSF5LFVPQkX2Ao/h1hl277/xtFGrpB4gXcVXNRQPC+qPT8mt39sflvXtn0QvaCZojObVLMIvvF4pypA71rtFCC3heJRmBlfVEMi6zignUVDOaB0RUx619gGlyVn1QFr+StHliQRhJFBuBfwvxhPGi3jXVneQL+0QNGMovXth8=
  - secure: BQSxiuhnQzgLFi7X911vWSUBtiou+bsNGFGN3jOHmi5pDbdsOH+JYAUuPVrLdLFzjkqcRvK9C1Pc4lkxDRKlfJCGFaZeJMvEYKGNdMtYU4QKOXt40fJdpBf9b95HZs6NNl2lvBE0/WfruqH+u68HQW5/RIeYc4roVkxwPVqcpc2syEn41UU1mjiFy8VSWBkDy/vs6xqueQ8D6PPytk7D8/13SySplT/Eb61MWgnPe879bsvrEHOnAGG65Dx8B9J25yFQog+u9Qms9RDtSt3H54tIOnmu9Yck+XGuYlmU7bTfPIAivSzkfbI/2K2JoiYm6SwvTzbHtDN83hyL+V+SVl+xO7UEoWC6WcsSV4vm7QXob9qX+M2stxYuq6wGZCJPjDk2HGIDOnWBWBdW+j733Bh0EE8g6DktWgOAL/zCWcu0Y38Qc7gYx+L7FpJtrL0Rt+wzlBfs078MnYEZ60PAJC18OL26JHKzIvDjXimdR+zravtSeyJqPwDFr76Id1o4mldKA1z0zysgmg7ecCA7maGVgFAj/b8nFUGXGgscg6XY9JXTzLGru/5xXsix/BliFeM8/LpiqpAOeRw5Ik7TyXp1jPhikqpKsPR9rPPPtDYPYA9ZXzPK2vHM6McHHZzzMegOABuagrhGgmefRloQgiQRQdBd6XE5Gn3JyrT1X0I=
  - secure: adXHOsYuBxP+rxAhmJsldCKFpG2itB29sEjUyqW1sjGYl30T7wO7S6m7EGUWcXETV327aEDfVzmelBgRynin9AMF7L5jB/7tBNmIz1Rl8llA3HSavlmiu5qCEIOG5Fngfi3CvYlf3S0oeEtcwZCZtQVnkUlBonKMQ12o/ZIkn/WcXT+1LKB4u85nnznMCacLJw43HJEqcVLTLx2hTjBUS4S0cVX+8hUZhoU0rbU8jxtEp2RfsSjOt1MBm7bB+u7Rzbi4kj/Kr8DZUAOuqpW9qn6K3lWM8x/7OyLGzDoIbmPmQILTKUCMm7mvzyxMDhJyMLv8kvjB4xir6b4+3lw+ckCCcjCva3kjdu7aQPZMfv1yq5n7rAXA3u/ItzbKlucnVg9DyhiidfAtc9DkjpfccQVSdwMEacYSsWUewNwaOUon0MnpN4YxaoAgXK2C+PjLp+DdZRqzzJYsMYjABTiDTHEyAZpYzIcb6J2if0V12lHxDfehYNnNTDrqwPpxzuq67IajOKaB7w3PcoHWl1iWly+wEManJBeLYrUpINu+1CLta6orGZPhvOi43xu1snc5QI+dB1Y81TB3NQUlTEqiWYWib4DjCrgAZUX6WJ5OyHPyl6aWSEkSgmsddPzRAtzHbKf3H27+PeE3zb5VnmLCoi+C3b8HuIHNXPx2rsiBn24=

before_deploy:
  - sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    tags: true
